spring.application.name=SimLab
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
# spring.datasource.url=jdbc:mysql://
# spring.datasource.username=
# spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

